name: Prepare results
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Prepare Firebase token
        id: prepare-firebase-token
        run: echo $FIREBASE_TOKEN | base64 --decode > ./lib/bike-path-quality-firebase-adminsdk-cgjm5-640ce5b722.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pyrebase
      - name: Run main script
        run: |
          python main.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: data/measurements/json/*.json
          commit_message: 'data: update measurement data'
