name: Prepare results
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Prepare Firebase token
        id: prepare-firebase-token
        run: echo $FIREBASE_TOKEN | base64 --decode > ./lib/bike-path-quality-firebase-adminsdk-cgjm5-640ce5b722.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Debug
        id: debug
        run: ls -l ./lib
